version: '3'

services:
  app:
    image: ${DOCKER_USERNAME}/myapp:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}  
    volumes:
      - ./app:/app
    depends_on:
      - redis  # Redis가 먼저 시작되어야 앱이 시작됨
  
  redis:
    image: "redis:latest"  # Redis 최신 이미지 
    ports:
      - "6379:6379"  # Redis 포트
    volumes:
      - redis-data:/data  # Redis 데이터 저장을 위한 볼륨 설정
   
   
 nginx:
    image: nginx:latest  # Nginx 최신 이미지
    ports:
      - "80:80"   # HTTP 포트
      - "443:443" # HTTPS 포트
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Nginx 설정 파일 
      - ./certs:/etc/nginx/certs  # SSL 인증서 
    depends_on:
      - app  # Nginx가 앱이 실행된 후 시작되도록 설정

volumes:
  redis-data: #도커가 볼륨을 자동으로 관리하도록 설
