name: Get GitHub Actions Public IP

on: 
  workflow_dispatch:  # 수동 트리거로 워크플로우 실행

jobs:
  get_ip:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get GitHub Actions Public IP
        id: ip
        uses: haythem/public-ip@v1.3
        
      - name: Show IP
        run: echo "GitHub Actions IP: ${{ steps.ip.outputs.ipv4 }}"
